### ISSUE TITLE
.PT Models not found on JD disk

### ISSUE THREAD

**Issue by Qubitium** [zanchangtong/Vega-MT#2]
There are only zh-en and en-zh sentencepiece models there and none of the actually trained .pt trained models. 

```
zh.spm.bpe.model
en.spm.bpe.model
```

The readme and script references  the following .pt files/models which doesn't exist for download.

```
vega_mt.enzh.pt
vega_mt.zhen.pt
```

Thanks. Was hoping to try out the en-zh translation to see it how it compared with others.

**Comment by zanchangtong** [comment]
Hi, Thanks for your interest in our work. Currently, our En-Zh and Zh-En models are being reviewed internally by the company. We will update the repository as soon as possible. In the future, we will provide API for evaluation.Best regard,Changtong
    
    
        
        

        
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/3/2023 14:41
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [zanchangtong/Vega-MT] .PT Models not found on JD disk (Issue #2)
        
      
    
  
  
There are only zh-en and en-zh sentencepiece models there and none of the actually trained .pt trained models.
zh.spm.bpe.model
en.spm.bpe.model

Thanks. Was hoping to try out the en-zh translation to see it how it compared with others.

**Comment by Qubitium** [comment]
Then please change your readme to show that the models cannot be downloaded. The readme clearly says the JD disk contains the models but it doesn't.
